community_engine_webservice/src/Entity/Call.php
<?php

namespace App\Entity;

use App\Repository\CallRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * @ORM\Entity(repositoryClass=CallRepository::class)
 * @ORM\Table(name="`call`")
 * @ORM\HasLifecycleCallbacks
 */
class Call
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $callDate;

    /**
     * @ORM\OneToMany(targetEntity=CallUser::class, mappedBy="callInstance")
     */
    private $users;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $uuid;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="connect")
     */
    private $reviews;

    /**
     * @ORM\Column(type="datetime", options={"default": "CURRENT_TIMESTAMP"})
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity=ConnectNote::class, mappedBy="connect")
     */
    private $connectNotes;

    /**
     * Use in crud admin as virtual field
     */
    public $userList;

    /**
     * @ORM\ManyToOne(targetEntity=Community::class, inversedBy="calls")
     */
    private $community;

    public function __construct()
    {
        $this->callDate = new \DateTime('next Thursday');
        $this->users = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->setCreatedAt(new \DateTime());
        $this->connectNotes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCallDate(): ?\DateTimeInterface
    {
        return $this->callDate;
    }

    public function setCallDate(?\DateTimeInterface $callDate): self
    {
        $this->callDate = $callDate;

        return $this;
    }

    /**
     * @return Collection|CallUser[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(CallUser $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setCallInstance($this);
        }

        return $this;
    }

    public function removeUser(CallUser $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getCallInstance() === $this) {
                $user->setCallInstance(null);
            }
        }

        return $this;
    }

    public function getUuid()
    {
        return $this->uuid;
    }

    public function setUuid($uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function onPrePersist()
    {
        $this->uuid = Uuid::uuid4()->toString();
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setConnect($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getConnect() === $this) {
                $review->setConnect(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return implode("\n", $this->getUsers()->toArray());
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @param User $user
     * @return Collection|CallUser[]
     */
    public function getCallUsersNot(User $user)
    {
        return $this->getUsers()->filter(function (CallUser $callUser) use ($user) {
            return $callUser->getUser() && $callUser->getUser()->getId() != $user->getId();
        });
    }

    /**
     * @return Collection|ConnectNote[]
     */
    public function getConnectNotes(): Collection
    {
        return $this->connectNotes;
    }

    public function addConnectNote(ConnectNote $connectNote): self
    {
        if (!$this->connectNotes->contains($connectNote)) {
            $this->connectNotes[] = $connectNote;
            $connectNote->setConnect($this);
        }

        return $this;
    }

    public function removeConnectNote(ConnectNote $connectNote): self
    {
        if ($this->connectNotes->contains($connectNote)) {
            $this->connectNotes->removeElement($connectNote);
            // set the owning side to null (unless already changed)
            if ($connectNote->getConnect() === $this) {
                $connectNote->setConnect(null);
            }
        }

        return $this;
    }

    public function getUserObjects()
    {
        return $this->getUsers()->map(function (CallUser $callUser) {
            return $callUser->getUser();
        });
    }

    public function getCommunity(): ?Community
    {
        return $this->community;
    }

    public function setCommunity(?Community $community): self
    {
        $this->community = $community;

        return $this;
    }
}

community_engine_webservice/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface;

class UserType extends AbstractType
{
    /**
     * @var Security
     */
    private $security;

    /**
     * UserType constructor.
     * @param Security $security
     */
    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if ($this->security->getUser() && empty($this->security->getUser()->getEmail())) {
            $builder
                ->add('emailAlt', null, [
                    'label' => 'E-mail',
                ]);
        }

        $builder
            ->add('firstName')
            ->add('lastName')
//            ->add('telegramUsername')
            ->add('facebookLink')
            ->add('linkedinLink')
            ->add('calendlyLink')
            ->add('about', TextareaType::class, [
                'label' => 'What is your expertise?',
                'help' => 'Current place of work, skills, experience',
            ])
//            ->add('looking_for', TextareaType::class)
            ->add('save', SubmitType::class)
//            ->add('answers', CollectionType::class, [
//                'entry_type' => AnswerType::class,
//                'entry_options' => ['label' => false],
//            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'validation_groups' => ['create_profile'],
        ]);
    }
}

community_engine_webservice/src/Controller/User/BalanceController.php
<?php

namespace App\Controller\User;

use App\Entity\Certificate;
use App\Exception\Balance\BalanceHandlerException;
use App\Repository\CertificateRepository;
use App\Service\Balance\BalanceHandlerService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class BalanceController extends AbstractController
{
    /**
     * @var BalanceHandlerService
     */
    private $balanceHandlerService;
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;
    /**
     * @var RequestStack
     */
    private $requestStack;

    /**
     * BalanceController constructor.
     * @param BalanceHandlerService $balanceHandlerService
     * @param EntityManagerInterface $entityManager
     * @param RequestStack $requestStack
     */
    public function __construct(
        BalanceHandlerService $balanceHandlerService,
        EntityManagerInterface $entityManager,
        RequestStack $requestStack
    )
    {
        $this->balanceHandlerService = $balanceHandlerService;
        $this->entityManager = $entityManager;
        $this->requestStack = $requestStack;
    }

    /**
     * @Route("/user/balance/certificate", name="user_balance_certificate")
     * @param TranslatorInterface $translator
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws \Throwable
     */
    public function certificate(TranslatorInterface $translator)
    {
        /** @var CertificateRepository $repository */
        $repository = $this->entityManager->getRepository(Certificate::class);
        $certificate = $repository->findOneBy([
            'code' => $this->requestStack->getCurrentRequest()->get('code'),
        ]);

        if ($certificate instanceof Certificate) {
            $deposit = new \App\Service\Payment\Deposit\Certificate($certificate, $this->getUser());
            try {
                $this->balanceHandlerService->handle($deposit);
                $this->addFlash('success', 'Ваш баланс успешно пополнен!');
            } catch (BalanceHandlerException $e) {
                $this->addFlash('danger', $translator->trans($e->getMessage()));
            }
        } else {
            $this->addFlash('danger', $translator->trans('Certificate not found'));
        }

        return $this->redirectToRoute('user_profile_notify');
    }
}

community_engine_webservice/src/Controller/User/CallController.php
<?php

namespace App\Controller\User;

use App\Entity\Call;
use App\Entity\CallUser;
use App\Entity\ConnectNote;
use App\Repository\CallRepository;
use App\Repository\CallUserRepository;
use App\Repository\ConnectNoteRepository;
use App\Service\Calendar\ICalService;
use App\Service\Call\ConnectCallService;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class CallController
 * @package App\Controller
 */
class CallController extends AbstractController
{
    /**
     * @var ConnectCallService
     */
    protected $connectCallService;

    /**
     * @var EntityManagerInterface
     */
    protected $entityManager;
    /**
     * @var Request
     */
    private $request;

    /**
     * CallController constructor.
     * @param ConnectCallService $connectCallService
     * @param EntityManagerInterface $entityManager
     * @param RequestStack $request
     */
    public function __construct(
        ConnectCallService $connectCallService,
        EntityManagerInterface $entityManager,
        RequestStack $request
    )
    {
        $this->connectCallService = $connectCallService;
        $this->entityManager = $entityManager;
        $this->request = $request->getCurrentRequest();
    }

    /**
     * @Route("/user/network", name="call_list")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function list(PaginatorInterface $paginator, Request $request)
    {
        if (!$this->getUser()->getProfileComplete()) {
            return $this->redirectToRoute('user_profile_create');
        }

        /** @var CallRepository $repository */
        $repository = $this->entityManager->getRepository(Call::class);
        $callsQuery = $repository->findByUserQuery($this->getUser());

        $pagination = $paginator->paginate(
            $callsQuery,
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('user/call/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }

    /**
     * @Route("/user/network/{callUuid}", name="call_detail")
     * @param string $callUuid
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function detail(string $callUuid, ICalService $calService)
    {
//        $calService->createICalFile();
//        dd();
//        /** @var CallRepository $repository */
//        $repository = $this->entityManager->getRepository(Call::class);
//        $call = $repository->findOneBy([
//            'uuid' => $callUuid,
//        ]);
//        if ($call instanceof Call) {
//            return $this->render('user/call/detail2.html.twig', [
////                'session_id' => $this->connectCallService->getSessionId($this->getUser(), $call),
//                'call_uuid' => $call->getUuid(),
//            ]);
//        }

        throw new NotFoundHttpException();
    }

    /**
     * @Route("/user/network/note/{callUuid}/{noteId?}", name="call_save_note", methods={"POST"})
     * @param string $callUuid
     * @param int|null $noteId
     * @return JsonResponse
     */
    public function saveNote(string $callUuid, ?int $noteId)
    {
        if (!$this->request->get('content')) {
            return new JsonResponse([
                'status' => 'success',
            ]);
        }

        /** @var CallRepository $repository */
        $repository = $this->entityManager->getRepository(Call::class);
        $call = $repository->findOneBy([
            'uuid' => $callUuid,
        ]);

        if (!($call instanceof Call)) {
            return new JsonResponse([
                'status' => 'success',
            ]);
        }

        if ($noteId) {
            /** @var ConnectNoteRepository $repository */
            $repository = $this->entityManager->getRepository(ConnectNote::class);
            $note = $repository->findOneBy([
                'id' => $noteId,
                'user' => $this->getUser(),
            ]);
            if (!$note) {
                return new JsonResponse([
                    'status' => 'success',
                ]);
            }
        } else {
            $note = new ConnectNote();
            $note->setUser($this->getUser());
            $note->setConnect($call);
        }

        $note->setContent($this->request->get('content'));
        $this->entityManager->persist($note);
        $this->entityManager->flush();

        return new JsonResponse([
            'status' => 'success',
            'noteId' => $note->getId(),
        ]);
    }

//    /**
//     * @Route("/call/peer-link/{callUuid}/{peerId}", name="call.peer-link")
//     * @param string $callUuid
//     * @param string $peerId
//     * @return JsonResponse
//     */
//    public function setPeerId(string $callUuid, string $peerId)
//    {
//        dd($peerId);
//        /** @var CallRepository $repository */
//        $repository = $this->entityManager->getRepository(Call::class);
//        $call = $repository->findOneBy([
//            'uuid' => $callUuid,
//        ]);
//        if ($call instanceof Call && $this->connectCallService->savePeerId($this->getUser(), $call, $peerId)) {
//            return new JsonResponse([
//                'state' => 'success',
//            ]);
//        }
//
//        return new JsonResponse([
//            'state' => 'error',
//        ]);
//    }

    /**
     * @Route("/user/call/peer-id/{callUuid}", name="call.peer-id")
     * @param string $callUuid
     * @return JsonResponse
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getRemotePeerId(string $callUuid)
    {
        /** @var CallRepository $repository */
        $repository = $this->entityManager->getRepository(Call::class);
        $call = $repository->findOneBy([
            'uuid' => $callUuid,
        ]);

        if ($call instanceof Call) {
            /** @var CallUserRepository $repositoryCallUser */
            $repositoryCallUser = $this->entityManager->getRepository(CallUser::class);
            $userCall = $repositoryCallUser->findRemoteUserCall($this->getUser(), $call);
            if (!$userCall || !$userCall->getUser()) {
                return new JsonResponse([]);
            }
            return new JsonResponse([
                'id' => $this->connectCallService->getSessionId($userCall->getUser(), $call),
            ]);
        }

        return new JsonResponse([]);
    }
}

community_engine_webservice/templates/user/call/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Meetsup Community Networking{% endblock %}

{% block body %}
    <style>
        #video-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, 300px);
            grid-auto-rows: 300px;
        }

        video {
            width: 100%;
            height: 100%;
            object-fit: cover;
            /*border-radius: 100%;*/
        }
    </style>
    <main id="main">

        <!-- ======= Breadcrumbs ======= -->
        <section id="breadcrumbs" class="breadcrumbs">
            <div class="container">

                <ol>
                    <li><a href="/">Home</a></li>
                    <li>Call</li>
                </ol>
                <h2>Video call</h2>

            </div>
        </section><!-- End Breadcrumbs -->

        <section class="inner-page pt-4">
            <div class="container">
                {#<div id="video-grid">#}
                    {#<video id="local-video" playsinline data-call-id="{{ call_uuid }}"#}
                           {#data-session-id="{{ session_id }}"#}
                           {#muted="muted" width="400px" height="auto" class="video-on"></video>#}
                    {#<video id="remote-video" playsinline width="400px" height="auto" class="video-on"></video>#}
                {#</div>#}
                {#<div>#}

                {#</div>#}
            </div>
        </section>

    </main>
{% endblock %}

{% block javascripts %}
    {#<script src="/assets/js/peerjs.min.js"></script>#}
    {#<script src="/assets/js/videochat.js"></script>#}
{% endblock %}

community_engine_webservice/templates/user/call/detail2.html.twig
{% extends 'base.html.twig' %}

{% block title %}Meetsup Community Networking{% endblock %}

{% block body %}
    <main id="main">

        <!-- ======= Breadcrumbs ======= -->
        <section id="breadcrumbs" class="breadcrumbs d-none d-lg-block bg-light">
            <div class="container">
                {% include 'user/profile/_nav.html.twig' %}
            </div>
        </section><!-- End Breadcrumbs -->

        <section class="inner-page pt-4">
            <div class="container">
                <div id="disqus_thread"></div>
                <script>
                    /**
                     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */

                    var disqus_config = function () {
                        this.page.url = '{{ app.request.uri }}';  // Replace PAGE_URL with your page's canonical URL variable
                        this.page.identifier = '{{ call_uuid }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                    };

                    (function () { // DON'T EDIT BELOW THIS LINE
                        var d = document, s = d.createElement('script');
                        s.src = 'https://meetsup.disqus.com/embed.js';
                        s.setAttribute('data-timestamp', +new Date());
                        (d.head || d.body).appendChild(s);
                    })();
                </script>
                <noscript>Please enable JavaScript to view the
                    <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
                </noscript>
            </div>
        </section>
    </main>

{% endblock %}

community_engine_webservice/templates/user/call/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Meetsup Community Networking{% endblock %}

{% block stylesheets %}
    <style>
        .profile-avatar {
            min-height: 220px;
            height: 100%;
            border: 0;
            background: center / cover no-repeat;
        }
    </style>
{% endblock %}

{% block body %}
    <main id="main">

        <!-- ======= Breadcrumbs ======= -->
        <section id="breadcrumbs" class="breadcrumbs d-none d-lg-block bg-light">
            <div class="container">
                {% include 'user/profile/_nav.html.twig' %}
            </div>
        </section><!-- End Breadcrumbs -->

        <section class="inner-page pt-4">
            <div class="container">
                {# total items count #}
                {#<div class="count">#}
                {#{{ pagination.getTotalItemCount }}#}
                {#</div>#}
                {#<table>#}
                {#<tr>#}
                {# sorting of properties based on query components #}
                {#<th>{{ knp_pagination_sortable(pagination, 'Id', 'c.id') }}</th>#}
                {#<th{% if pagination.isSorted('c.uuid') %} class="sorted"{% endif %}>#}
                {#{{ knp_pagination_sortable(pagination, 'Uuid', 'c.uuid') }}#}
                {#</th>#}
                {#<th{% if pagination.isSorted('c.created_at') %} class="sorted"{% endif %}>#}
                {#{{ knp_pagination_sortable(pagination, 'Created At', 'c.created_at') }}#}
                {#</th>#}
                {#</tr>#}
                {#</table>#}
                {% if pagination is empty %}
                    <div class="mt-5 mb-5">
                        <p>
                            {% trans %}Soon there will be contact details and other information about the chosen partners for meetings{% endtrans %}
                        </p>
                    </div>
                {% endif %}
                {% for call in pagination %}
                    {% set user = call.getCallUsersNot(app.user).first() %}
                    {% if user %}
                        {% set user = user.getUser() %}
                        <div class="card mb-3">
                            <div class="row no-gutters">
                                <div class="col-md-2">
                                    <div class="card-img profile-avatar"
                                         style="background-image: url('{{ user.getPictureUrl() }}'); z-index: 99;">
                                    </div>
                                </div>
                                <div class="col-md-10">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ user.getFirstName()|e }} {{ user.getLastName()|e }}</h5>
                                        <div>
                                            {{ user.about|e }}
                                        </div>
                                        <div class="card-text">
                                            <small>
                                                <strong>E-Mail:</strong> <a
                                                        href="mailto:{{ user.email|e }}">{{ user.email|e }}</a>
                                                {{ user.facebookLink ? ("<br/><strong>Facebook:</strong> <a target=\"_blank\" href=\"" ~ user.facebookLink|e ~ "\">" ~ user.facebookLink|e ~ "</a>")|raw }}
                                                {{ user.linkedinLink ? ("<br/><strong>LinkedIn:</strong> <a target=\"_blank\" href=\"" ~ user.linkedinLink|e ~ "\">" ~ user.linkedinLink|e ~ "</a>")|raw }}
                                                {{ user.telegramUsername ? ("<br/><strong>Telegram:</strong> <a href=\"tg://resolve?domain=" ~ user.telegramUsername|e ~ "\">" ~ user.telegramUsername|e ~ "</a>")|raw }}
                                                {% for question in user.getQuestions() %}
                                                    <br/><strong>{{ question.getDeclarativeTitle() }}
                                                    :</strong> {{ question.getAnswers()|e }}
                                                {% endfor %}
                                            </small>
                                        </div>
                                        <div class="card-text">
                                            <small class="text-muted">
                                                {% trans %}The meeting date{% endtrans %}
                                                : {{ call.createdAt|date('d.m.Y') }}
                                            </small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="row">
                                    {% set note = call.getConnectNotes().first() %}
                                    <textarea oninput="autoGrow(this)"
                                              data-connect-id="{{ call.getUuid() }}"
                                              data-note-id="{{ note ? note.getId() }}"
                                              class="text-note form-control"
                                              placeholder="{% trans %}Your notes{% endtrans %}">{{ note }}</textarea>
                                </div>
                                <div class="row">
                                    <div class="col-md-7 mt-2">
                                        <small>
                                            {% trans %}Here you can leave the outcomes of the meeting, such as possible topics and offers to the partner. The information is visible only to you.{% endtrans %}
                                        </small>
                                    </div>
                                    <div class="col-md-5 mt-3">
                                        <button class="btn btn-info rounded-pill pull-right save-note">
                                            {% trans %}Save{% endtrans %}
                                        </button>
                                        <div class="spinner-border text-success pull-right mt-1 mr-4 d-none"
                                             role="status">
                                            <span class="sr-only">Loading...</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                {# display navigation #}
                <br/>
                <div class="navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>
            </div>
        </section>

    </main>
{% endblock %}

{% block javascripts %}
    <script>
        function autoGrow(element) {
            element.style.height = "76px";
            element.style.height = (element.scrollHeight) + "px";
        }

        $(() => {
            $(".text-note").each(function (textarea) {
                $(this).height($(this)[0].scrollHeight);
            });

            $(document).on('click', '.save-note', (e) => {
                let textarea = $(e.target).closest('.card-footer').find('textarea'),
                    spinner = $(e.target).closest('.card-footer').find('.spinner-border'),
                    connectId = textarea.data('connect-id'),
                    noteId = textarea.data('note-id'),
                    noteIdUrlSegment = noteId === '' ? '' : '/' + noteId;

                spinner.removeClass('d-none');

                $.ajax({
                    type: "POST",
                    dataType: 'json',
                    url: "/user/network/note/" + connectId + noteIdUrlSegment,
                    data: {
                        content: textarea.val()
                    },
                    success: (response) => {
                        if (response.noteId !== undefined) {
                            textarea.data('note-id', Number(response.noteId));
                        }
                        spinner.addClass('d-none');
                    }
                });
            });
        });
    </script>
{% endblock %}